# Generated by Django 3.1.7 on 2021-03-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=5)),
                ('cpu', models.CharField(max_length=10)),
                ('ram', models.IntegerField()),
                ('hdd', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='photo/%y/%m')),
            ],
        ),
    ]
