# Generated by Django 3.1.7 on 2021-03-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210325_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='company',
            field=models.CharField(choices=[('asus', 'asus'), ('lg', 'lg'), ('toshiba', 'toshiba'), ('acer', 'acer'), ('dell', 'dell')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='model',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
