# Generated by Django 3.1.7 on 2021-03-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210325_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='test',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
