# Generated by Django 3.1.7 on 2021-03-25 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_laptop_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dateclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='%y%m%d')),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='cpu',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
