# Generated by Django 3.1.7 on 2021-03-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210325_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateclass',
            options={'verbose_name': 'Birthday Date'},
        ),
        migrations.AlterField(
            model_name='dateclass',
            name='date',
            field=models.DateField(help_text='Enter your birthday', verbose_name='%y%m%d'),
        ),
    ]
