# Generated by Django 3.1.7 on 2021-03-25 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210325_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateclass',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='dateclass',
            name='time',
            field=models.TimeField(verbose_name='Time if job'),
        ),
    ]
