# Generated by Django 3.1.7 on 2021-03-26 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210325_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateclass',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created'),
        ),
    ]
